project:
  type: book
  output-dir: /home/kirkpatj/Packages/autoquarto/tests/testOutput
book:
  title: What is the title?
  author: Who Is The Author
  date: "`r format(Sys.Date())` at `r format(Sys.Time())` on `r Sys.info()[['nodename']]`"
  chapters:
  - index.qmd
  - intro.qmd
  - body.qmd
  - conclusion.qmd
  - environment.qmd
  output-file: testReport
format:
  html:
    theme: cosmo
  pdf: default

